site_name: MCPI-Revival
site_url: https://mcpi-revival.github.io/docs
repo_url: https://github.com/MCPI-Revival/docs
site_description: 'Minecraft: Pi Edition: Revival Project'

theme: readthedocs

exclude_docs: SUMMARY.md

plugins:
  - search
  - gh-admonitions
  - literate-nav:
        markdown_extensions:
          - sane_lists
          - mdx_truly_sane_lists

markdown_extensions:
  - admonition
  - footnotes
  - sane_lists
  - mdx_truly_sane_lists
  - pymdownx.superfences
